version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cicd-prac
    networks:
      - dnetwork
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - dnetwork
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    depends_on:
      spring-app:
        condition: service_healthy
    command: ["nginx", "-g", "daemon off;"]

  nginx-validator:
    image: nginx:latest
    container_name: nginx-validator
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    entrypoint: ["nginx", "-t", "-c", "/etc/nginx/nginx.conf"]
    networks:
      - dnetwork
    restart: "no"

networks:
  dnetwork:
    driver: bridge
